### ISSUE TITLE
Некорректная  проверка на время последнего обновления

### ISSUE THREAD

**Issue by kriteimk** [Animehin/PolySchedule_bot#20]
https://github.com/Animehin/PolySchedule_bot/blob/40b8eec282edebf659325aeb3db722635885d2fc/DataBase/Schedule.py#L35
Должно быть
`if (pgroup not in last_updated) or (last_updated[pgroup] is not datetime.date.today()):`
И добавить `last_updated[pgroup]=datetime.date.today()`

**Comment by Animehin** [comment]
#21
